#!/usr/bin/env bash
# Phase 12 close gate — v3.3.0 (Bash equivalent of scripts/phase-12-close.ps1)
# ---------------------------------------------------------------------------
# Honors:
#   - Phase 3 D-15 byte-identical psql \l SHA-256 invariant
#     (baseline 0d98b0de57125b164489958eef5fc3da26969d18a7ef8bba845da02f20aac127)
#   - TEST-REDIS-04: docker exec sk-redis redis-cli --scan | LC_ALL=C sort | sha256sum
#     BEFORE = AFTER across the full suite (locale-locked per RESEARCH Pitfall 6)
#   - Phase 3 D-18 3-consecutive-GREEN cadence
#
# Usage:
#   bash scripts/phase-12-close.sh
#
# Exit codes:
#   0  — all three runs GREEN, both SHA-256 invariants held
#   1  — invariant violation OR any test run RED
#   2  — environment misconfigured
# ---------------------------------------------------------------------------

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "Phase 12 close gate starting from $REPO_ROOT"

# ---- Pre-flight: compose stack healthy ----
echo "Pre-flight: compose stack health check..."
for svc in postgres redis elasticsearch prometheus; do
    health=$(docker compose ps "$svc" --format json | jq -r '.[].Health' 2>/dev/null || echo "missing")
    if [[ "$health" != "healthy" ]]; then
        echo "Service '$svc' is not healthy (Health=$health). Aborting." >&2
        exit 2
    fi
done

# ---- BEFORE snapshots ----
echo "Capturing BEFORE snapshots..."

# (a) Phase 3 D-15 psql \l invariant
BEFORE_PG=$(docker exec sk-postgres psql -U postgres -lqt)
BEFORE_PG_HASH=$(printf '%s' "$BEFORE_PG" | sha256sum | awk '{print $1}')
echo "  psql \\l SHA-256 BEFORE = $BEFORE_PG_HASH"

# (b) TEST-REDIS-04 redis-cli --scan invariant — locale-locked per Pitfall 6.
BEFORE_REDIS=$(docker exec sk-redis redis-cli --scan | LC_ALL=C sort)
BEFORE_REDIS_HASH=$(printf '%s' "$BEFORE_REDIS" | sha256sum | awk '{print $1}')
echo "  redis-cli --scan SHA-256 BEFORE = $BEFORE_REDIS_HASH"

# ---- 3-GREEN cadence (Phase 3 D-18) ----
PASSED_COUNTS=()
for i in 1 2 3; do
    echo "Run $i of 3: dotnet test..."
    START=$(date +%s)
    if ! OUTPUT=$(dotnet test tests/BaseApi.Tests/BaseApi.Tests.csproj --configuration Release --no-build 2>&1); then
        echo "Run $i FAILED." >&2
        echo "Per Phase 8 Plan 08-08 precedent: known-flake observability (LogLevelFilterTests" >&2
        echo "  OTel cold-start) or ConcurrencyTokenTests racing-writes may justify a retry." >&2
        echo "$OUTPUT" >&2
        exit 1
    fi
    END=$(date +%s)
    PASSED=$(echo "$OUTPUT" | grep -oE 'Passed:\s+[0-9]+' | head -1 | grep -oE '[0-9]+' || echo "-1")
    PASSED_COUNTS+=("$PASSED")
    echo "  Run $i — Passed=$PASSED, Duration=$((END - START))s"
done

# All three runs must have the same Passed count
if [[ "${PASSED_COUNTS[0]}" != "${PASSED_COUNTS[1]}" || "${PASSED_COUNTS[1]}" != "${PASSED_COUNTS[2]}" ]]; then
    echo "3-GREEN cadence violation — fact counts diverge: ${PASSED_COUNTS[*]}" >&2
    exit 1
fi
PASSED_TOTAL="${PASSED_COUNTS[0]}"
echo "3-GREEN cadence passed — $PASSED_TOTAL facts GREEN across 3 runs."

# ---- AFTER snapshots ----
echo "Capturing AFTER snapshots..."
AFTER_PG=$(docker exec sk-postgres psql -U postgres -lqt)
AFTER_PG_HASH=$(printf '%s' "$AFTER_PG" | sha256sum | awk '{print $1}')
echo "  psql \\l SHA-256 AFTER  = $AFTER_PG_HASH"

AFTER_REDIS=$(docker exec sk-redis redis-cli --scan | LC_ALL=C sort)
AFTER_REDIS_HASH=$(printf '%s' "$AFTER_REDIS" | sha256sum | awk '{print $1}')
echo "  redis-cli --scan SHA-256 AFTER  = $AFTER_REDIS_HASH"

# ---- Invariant assertions ----
ALL_GOOD=1

if [[ "$BEFORE_PG_HASH" != "$AFTER_PG_HASH" ]]; then
    echo "Phase 3 D-15 INVARIANT VIOLATED: psql \\l SHA-256 BEFORE != AFTER" >&2
    echo "  BEFORE = $BEFORE_PG_HASH" >&2
    echo "  AFTER  = $AFTER_PG_HASH" >&2
    ALL_GOOD=0
else
    echo "Phase 3 D-15 invariant HELD: psql \\l SHA-256 = $AFTER_PG_HASH"
fi

if [[ "$BEFORE_REDIS_HASH" != "$AFTER_REDIS_HASH" ]]; then
    echo "TEST-REDIS-04 INVARIANT VIOLATED: redis-cli --scan SHA-256 BEFORE != AFTER" >&2
    echo "  BEFORE = $BEFORE_REDIS_HASH" >&2
    echo "  AFTER  = $AFTER_REDIS_HASH" >&2
    echo "  Investigate: 'docker exec sk-redis redis-cli --scan | grep test:cls-'" >&2
    ALL_GOOD=0
else
    echo "TEST-REDIS-04 invariant HELD: redis-cli --scan SHA-256 = $AFTER_REDIS_HASH"
fi

# ---- Negative schema-migration assertion ----
NEW_MIGRATIONS=$(git status --porcelain src/BaseApi.Service/Migrations/ 2>/dev/null || true)
if [[ -n "$NEW_MIGRATIONS" ]]; then
    echo "Unexpected EF migration changes under src/BaseApi.Service/Migrations/:" >&2
    echo "$NEW_MIGRATIONS" >&2
    ALL_GOOD=0
else
    echo "No EF migrations generated by Phase 12 (negative schema-push assertion HELD)."
fi

# ---- HEALTH-01..05 byte-immutable invariant ----
HEALTH_DIFF=$(git diff src/BaseApi.Core/Health/StartupCompletionService.cs src/BaseApi.Core/DependencyInjection/HealthServiceCollectionExtensions.cs)
if [[ -n "$HEALTH_DIFF" ]]; then
    echo "HEALTH-01..05 byte-immutable invariant VIOLATED — D-05/D-06 regression:" >&2
    echo "$HEALTH_DIFF" >&2
    ALL_GOOD=0
else
    echo "HEALTH-01..05 byte-immutable invariant HELD (D-05/D-06)."
fi

if [[ "$ALL_GOOD" != "1" ]]; then
    echo "Phase 12 close gate FAILED. Resolve violations and re-run." >&2
    exit 1
fi

echo "Phase 12 close gate PASSED."
echo "  Total facts GREEN: $PASSED_TOTAL"
echo "  psql \\l SHA-256:    $AFTER_PG_HASH"
echo "  redis-cli --scan SHA-256: $AFTER_REDIS_HASH"
echo "Operator: append these values to .planning/STATE.md Phase 12 P08 close entry."

exit 0
