// <auto-generated />
using System;
using BaseApi.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseApi.Service.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528074618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseApi.Service.Features.Assignment.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_assignments_step_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Processor.ProcessorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfigSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_schema_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("InputSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_schema_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OutputSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_schema_id");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_processors");

                    b.HasIndex("ConfigSchemaId")
                        .HasDatabaseName("ix_processors_config_schema_id");

                    b.HasIndex("InputSchemaId")
                        .HasDatabaseName("ix_processors_input_schema_id");

                    b.HasIndex("OutputSchemaId")
                        .HasDatabaseName("ix_processors_output_schema_id");

                    b.HasIndex("SourceHash")
                        .IsUnique()
                        .HasDatabaseName("uq_processor_source_hash");

                    b.ToTable("processors", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Schema.SchemaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_schemas");

                    b.ToTable("schemas", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Step.StepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EntryCondition")
                        .HasColumnType("integer")
                        .HasColumnName("entry_condition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("processor_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_steps");

                    b.HasIndex("ProcessorId")
                        .HasDatabaseName("ix_steps_processor_id");

                    b.ToTable("steps", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Step.StepNextSteps", b =>
                {
                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<Guid>("NextStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_step_id");

                    b.HasKey("StepId", "NextStepId")
                        .HasName("pk_step_next_steps");

                    b.HasIndex("NextStepId")
                        .HasDatabaseName("ix_step_next_steps_next_step_id");

                    b.ToTable("step_next_steps", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Workflow.WorkflowAssignments", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.HasKey("WorkflowId", "AssignmentId")
                        .HasName("pk_workflow_assignments");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_workflow_assignments_assignment_id");

                    b.ToTable("workflow_assignments", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Workflow.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Workflow.WorkflowEntrySteps", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("WorkflowId", "StepId")
                        .HasName("pk_workflow_entry_steps");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_workflow_entry_steps_step_id");

                    b.ToTable("workflow_entry_steps", (string)null);
                });

            modelBuilder.Entity("BaseApi.Service.Features.Assignment.AssignmentEntity", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Step.StepEntity", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_step_id");
                });

            modelBuilder.Entity("BaseApi.Service.Features.Processor.ProcessorEntity", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Schema.SchemaEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigSchemaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_processor_config_schema_id");

                    b.HasOne("BaseApi.Service.Features.Schema.SchemaEntity", null)
                        .WithMany()
                        .HasForeignKey("InputSchemaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_processor_input_schema_id");

                    b.HasOne("BaseApi.Service.Features.Schema.SchemaEntity", null)
                        .WithMany()
                        .HasForeignKey("OutputSchemaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_processor_output_schema_id");
                });

            modelBuilder.Entity("BaseApi.Service.Features.Step.StepEntity", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Processor.ProcessorEntity", null)
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_step_processor_id");
                });

            modelBuilder.Entity("BaseApi.Service.Features.Step.StepNextSteps", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Step.StepEntity", null)
                        .WithMany()
                        .HasForeignKey("NextStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_step_next_steps_next_step_id");

                    b.HasOne("BaseApi.Service.Features.Step.StepEntity", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_step_next_steps_step_id");
                });

            modelBuilder.Entity("BaseApi.Service.Features.Workflow.WorkflowAssignments", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Assignment.AssignmentEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_assignments_assignment_id");

                    b.HasOne("BaseApi.Service.Features.Workflow.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_assignments_workflow_id");
                });

            modelBuilder.Entity("BaseApi.Service.Features.Workflow.WorkflowEntrySteps", b =>
                {
                    b.HasOne("BaseApi.Service.Features.Step.StepEntity", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_entry_steps_step_id");

                    b.HasOne("BaseApi.Service.Features.Workflow.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_entry_steps_workflow_id");
                });
#pragma warning restore 612, 618
        }
    }
}
